
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PANDA
 */
public class ADD_CASE_OFFICER extends javax.swing.JDialog {

    /**
     * Creates new form ADD_CASE_OFFICER
     */
    public ADD_CASE_OFFICER() {
        initComponents();
        fillModel1();
        jComboBox2.addItem("Select Officer ID");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/imgonline-com-ua-Shape-BygoYj6PUn37hP.png"))); // NOI18N
        jLabel6.setText("ICRIME FIGHTER");

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Case Officer");

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Case ID : ");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Case Name : ");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Officer ID : ");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Officer Name : ");

        jComboBox1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, 150, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      jComboBox2.removeAllItems();
        MysqlDataSource m=new MysqlDataSource();
        m.setUser("root");
        m.setPassword("mysql");
        m.setDatabaseName("criminal_investigator");
        m.setServerName("localhost");
        m.setPortNumber(3306);
        try
        {
            Connection con=m.getConnection();
            if(jComboBox1.getSelectedIndex()==0)
                jTextField1.setText("");
            else
            {
                int id=Integer.parseInt(jComboBox1.getSelectedItem().toString());
                PreparedStatement ps=con.prepareStatement("Select case_name from case_detail where case_id=?");
                ps.setInt(1,id);
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                    jTextField1.setText(rs.getString("case_name"));
                }
            }
            fillModel2();
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        MysqlDataSource m=new MysqlDataSource();
        m.setUser("root");
        m.setPassword("mysql");
        m.setDatabaseName("criminal_investigator");
        m.setServerName("localhost");
        m.setPortNumber(3306);
        try
        {
            Connection con=m.getConnection();
            if(jComboBox2.getSelectedIndex()==0)
                jTextField2.setText("");
            else
            {
                int id=Integer.parseInt(jComboBox2.getSelectedItem().toString());
                PreparedStatement ps=con.prepareStatement("Select name from officer_details where officer_id=?");
                ps.setInt(1,id);
                ResultSet rs=ps.executeQuery();
                if(rs.next())
                {
                    jTextField2.setText(rs.getString("name"));
                }
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel7.setText("");
        if(jComboBox1.getSelectedIndex()==-1)
        {
            jLabel7.setText("Select a case ID");
            jComboBox1.requestFocus();
            return;
        }
        else if(jComboBox2.getSelectedIndex()==-1)
        {
            jLabel7.setText("Select an officer ID");
            jComboBox2.requestFocus();
            return;
        }
        MysqlDataSource m=new MysqlDataSource();
        m.setUser("root");
        m.setPassword("mysql");
        m.setDatabaseName("criminal_investigator");
        m.setServerName("localhost");
        m.setPortNumber(3306);
        try
        {
            Connection con=m.getConnection();
            PreparedStatement ps1=con.prepareStatement("Select max(rank) as mm from case_officers where case_id=?");
            ps1.setInt(1,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ResultSet rs=ps1.executeQuery();
            rs.next();
            int rank=rs.getInt("mm");
            rank++;
            PreparedStatement ps=con.prepareStatement("Insert into case_officers values(?,?,?)");
            ps.setInt(1,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ps.setInt(2,Integer.parseInt(jComboBox2.getSelectedItem().toString()));
            ps.setInt(3,rank);
            ps.executeUpdate();
           // jLabel7.setText("Case Officer added successfully.");
           JOptionPane.showMessageDialog(this,"Case officer added successfully");
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
         {
             jLabel7.setText("");
        if(jComboBox1.getSelectedIndex()==-1)
        {
            jLabel7.setText("Select a case ID");
            jComboBox1.requestFocus();
            return;
        }
        else if(jComboBox2.getSelectedIndex()==-1)
        {
            jLabel7.setText("Select an officer ID");
            jComboBox2.requestFocus();
            return;
        }
        MysqlDataSource m=new MysqlDataSource();
        m.setUser("root");
        m.setPassword("mysql");
        m.setDatabaseName("criminal_investigator");
        m.setServerName("localhost");
        m.setPortNumber(3306);
        try
        {
            Connection con=m.getConnection();
            PreparedStatement ps1=con.prepareStatement("Select max(rank) as mm from case_officers where case_id=?");
            ps1.setInt(1,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ResultSet rs=ps1.executeQuery();
            rs.next();
            int rank=rs.getInt("mm");
            rank++;
            PreparedStatement ps=con.prepareStatement("Insert into case_officers values(?,?,?)");
            ps.setInt(1,Integer.parseInt(jComboBox1.getSelectedItem().toString()));
            ps.setInt(2,Integer.parseInt(jComboBox2.getSelectedItem().toString()));
            ps.setInt(3,rank);
            ps.executeUpdate();
            //jLabel7.setText("Case Officer added successfully.");
            JOptionPane.showMessageDialog(this,"Case officer added successfully");
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
         }
    }//GEN-LAST:event_jButton1KeyPressed
 private void fillModel1()
    {
        MysqlDataSource m=new MysqlDataSource();
        m.setUser("root");
        m.setPassword("mysql");
        m.setDatabaseName("criminal_investigator");
        m.setServerName("localhost");
        m.setPortNumber(3306);
        try
        {
            Connection con=m.getConnection();
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("Select case_id from case_detail");
            int id;
            jComboBox1.addItem("Select Case ID");
            while(rs.next())
            {
                id=rs.getInt("case_id");
                jComboBox1.addItem(Integer.toString(id));
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
  private void fillModel2()
    {
        MysqlDataSource m=new MysqlDataSource();
        m.setUser("root");
        m.setPassword("mysql");
        m.setDatabaseName("criminal_investigator");
        m.setServerName("localhost");
        m.setPortNumber(3306);
        try
        {
            Connection con=m.getConnection();
            PreparedStatement stmt=con.prepareStatement("Select officer_id from officer_details where officer_id not in(Select officer_id from case_officers where case_id=?)");
            int i =Integer.parseInt((String)jComboBox1.getSelectedItem());
            stmt.setInt(1,i);
            ResultSet rs=stmt.executeQuery();
            int id;
            jComboBox2.addItem("Select Officer ID");
            while(rs.next())
            {
                id=rs.getInt("officer_id");
                jComboBox2.addItem(Integer.toString(id));
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_CASE_OFFICER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_CASE_OFFICER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_CASE_OFFICER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_CASE_OFFICER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_CASE_OFFICER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
