
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import javafx.scene.input.KeyCode;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PANDA
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        setLocationRelativeTo(null);           //to open the frame in the centre of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Username : ");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password : ");

        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Login");

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepackage/imgonline-com-ua-Shape-BygoYj6PUn37hP.png"))); // NOI18N
        jLabel5.setText("ICRIME FIGHTER");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPasswordField1.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N

        jButton2.setFont(new java.awt.Font("Century Schoolbook", 0, 12)); // NOI18N
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel4.setText("");
        if(jTextField1.getText().equals(""))
        {
            jLabel4.setText("Username field cannot be empty");
            jTextField1.requestFocus();            //to move the cursor to specific component
            return;
        }
        else if(new String(jPasswordField1.getPassword()).equals(""))
        {
            jLabel4.setText("Password Field cannot be empty");
            jPasswordField1.requestFocus();
            return;
        }
        String user=jTextField1.getText();
        String pswrd=new String(jPasswordField1.getPassword());
        if(pswrd.equals("password")) 
        {
            CHANGE_PASSWORD f=new CHANGE_PASSWORD(user);      //frame object created
            f.setModal(true); 
            f.setVisible(true);           
            return;
        }
        else
        {
            MysqlDataSource m=new MysqlDataSource();
            m.setUser("root");
            m.setPassword("mysql");
            m.setDatabaseName("criminal_investigator");
            m.setServerName("localhost");
            m.setPortNumber(3306);
            try{
            Connection con = m.getConnection();
            PreparedStatement ps=con.prepareStatement("Select role from login_details where username=? and password=md5(concat(password_salt,':',?))");
            ps.setString(1,user);
            ps.setString(2,pswrd);
            ResultSet rs=ps.executeQuery();
            int role;
            if(!rs.next())
            {
                jLabel4.setText("Invalid username and password");
                jTextField1.requestFocus();
                return;
            }
            else
            {
                role = rs.getInt("role");
            }
            switch(role)
            {
                case 1:
                        ADMIN_FORM f=new ADMIN_FORM(user);
                        JDialog f5=new JDialog(f,"Admin Form",true);
                        f.setVisible(true);
                        break;
                case 2:
                        OFFICER_FORM f1=new OFFICER_FORM(user);
                        JDialog f3=new JDialog(f1,"Officer Form",true);
                        f1.setVisible(true);
                        break;
                case 3:
                        GUEST_FORM f2=new GUEST_FORM();
                        JDialog f4=new JDialog(f2,"Guest Form",true);
                        f2.setVisible(true);
                        break;
            }
            jTextField1.setText("");
            jPasswordField1.setText("");
            }catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CREATE_ACCOUNT f=new CREATE_ACCOUNT();
        f.setModal(true);
        f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jLabel4.setText("");
        if(jTextField1.getText().equals(""))
        {
            jLabel4.setText("Username field cannot be empty");
            jTextField1.requestFocus();            //to move the cursor to specific component
            return;
        }
        else if(new String(jPasswordField1.getPassword()).equals(""))
        {
            jLabel4.setText("Password Field cannot be empty");
            jPasswordField1.requestFocus();
            return;
        }
        String user=jTextField1.getText();
        String pswrd=new String(jPasswordField1.getPassword());
        if(pswrd.equals("password")) 
        {
            CHANGE_PASSWORD f=new CHANGE_PASSWORD(user);      //frame object created
            f.setModal(true); 
            f.setVisible(true);           
            return;
        }
        else
        {
            MysqlDataSource m=new MysqlDataSource();
            m.setUser("root");
            m.setPassword("mysql");
            m.setDatabaseName("criminal_investigator");
            m.setServerName("localhost");
            m.setPortNumber(3306);
            try{
            Connection con = m.getConnection();
            PreparedStatement ps=con.prepareStatement("Select role from login_details where username=? and password=md5(concat(password_salt,':',?))");
            ps.setString(1,user);
            ps.setString(2,pswrd);
            ResultSet rs=ps.executeQuery();
            int role;
            if(!rs.next())
            {
                jLabel4.setText("Invalid username and password");
                jTextField1.requestFocus();
                return;
            }
            else
            {
                role = rs.getInt("role");
            }
            switch(role)
            {
                case 1:
                        ADMIN_FORM f=new ADMIN_FORM(user);
                        JDialog f5=new JDialog(f,"Admin Form",true);
                        f.setVisible(true);
                        break;
                case 2:
                        OFFICER_FORM f1=new OFFICER_FORM(user);
                        JDialog f3=new JDialog(f1,"Officer Form",true);
                        f1.setVisible(true);
                        break;
                case 3:
                        GUEST_FORM f2=new GUEST_FORM();
                        JDialog f4=new JDialog(f2,"Guest Form",true);
                        f2.setVisible(true);
                        break;
            }
            jTextField1.setText("");
            jPasswordField1.setText("");
            }catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
        }
    }//GEN-LAST:event_jButton1KeyPressed
//to click the button using enter key
    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            CREATE_ACCOUNT f=new CREATE_ACCOUNT();
            f.setModal(true);
            f.setVisible(true);
        }
    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try
                {
                    Thread.sleep(4500);
                }
                catch(Exception ex)
                {}
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
